import React, { useRef } from "react";

import html2canvas from "html2canvas";
import jsPDF from "jspdf";

const App = () => {
  const pdRef = useRef();
  const downloadPDF = () => {
    const input = pdRef.current;
    html2canvas(input).then((canvas) => {
      const imgData = canvas.toDataURL("image/png");
      const pdf = new jsPDF("p", "mm", "a4", false);
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = pdf.internal.pageSize.getHeight();
      const imgWidth = canvas.width;
      const imgHeight = canvas.height;
      const ratio = Math.min(pdfWidth / imgWidth, pdfHeight / imgHeight);
      const imgX = (pdfWidth - imgWidth * ratio) / 2;
      const imgY = 0;
      pdf.addImage(
        imgData,
        "PNG",
        imgX,
        imgY,
        imgWidth * ratio,
        imgHeight * ratio
      );
      pdf.save("invoice.pdf");
    });
  };
  return (
    <>
      <div className="p-10" ref={pdRef}>
        <div>
          <div>
            <span className="font-bold text-4xl ">REAs</span>
            <nav className="font-semibold flex gap-5">
              <span>Blog</span>
              <span>Categories</span>
              <span>Tags</span>
            </nav>
          </div>
          <div>
            <h1>The Joys of Buying Over Building</h1>
          </div>
          <main>
            <h2>Some features</h2>
            <div>
              <span>House 1</span>
              <span>House 2</span>
              <span>House 3</span>
            </div>
            <p className="mt-5">
              In the grand game of acquiring a new abode, the age-old debate
              between buying an existing house and building a brand-new one
              continues to captivate prospective homeowners. Both options have
              their merits, but let's take a lighthearted stroll through the
              perks of opting for a pre-built dwelling.
            </p>
            <p>
              Then there's the joy of exploring neighborhoods with character and
              history. Buying a house often means settling into an established
              community, complete with charming local spots and friendly
              neighbors. Sure, you might not have personally picked out every
              detail of your home, but there's a unique charm in discovering the
              stories embedded in its walls and the quirks that come with a
              house that's been lived in.
            </p>
            <p>
              In the end, whether you're swiping right on a charming existing
              home or swaying to the rhythm of your own construction symphony,
              the decision between buying and building is a personal one. But
              hey, there's something undeniably delightful about stepping into a
              house and immediately feeling at home – no hard hat required.
            </p>
            <p className="lower">Article generated by ChatGPT</p>
          </main>
        </div>
      </div>
      <button
        onClick={downloadPDF}
        className="mt-4 p-2 bg-blue-500 rounded-md ml-10"
      >
        Print article
      </button>
    </>
  );
};
export default App;
